### ISSUE TITLE
fix(Build analyze): Start a new build without Git

### ISSUE THREAD

**Issue by Jannchie** [nuxt/devtools#318]
### 🐛 The bug

Creating a new nuxt project does not initialize git by default, and when I use devtool for build analysis, clicking start a new build does not respond. An error message appears on the command line:

```
 ERROR  [nuxt-devtools] RPC error on executing "generateAnalyzeBuildName": fatal: not a git repository (or any of the parent directories): .git                                  15:47:27


  
  at Object.action (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:6000:25)
  at PluginStore.exec (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:6027:25)
  at /D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:3449:43
  at new Promise (<anonymous>)
  at GitExecutorChain.handleTaskData (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:3447:16)
  at GitExecutorChain.<anonymous> (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:3431:44)
  at Generator.next (<anonymous>)
  at fulfilled (/D:/Code/jannchie/node_modules/.pnpm/@nuxt+devtools@0.6.7_nuxt@3.6.2_vite@4.4.2/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:2244:24)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### 🛠️ To reproduce

Any nuxt project without git

### 🌈 Expected behavior

I think maybe the build analysis doesn't need to rely on git, it seems to be an error in generating the build name, maybe we can get a build name from somewhere else, like `package.json`?

**Comment by antfu** [comment]
Yeah we could do a try-catch fallback. Using build time string should be good enough I think
