### ISSUE TITLE
nuxt@3.2.0 can'not start nuxt

### ISSUE THREAD

**Issue by huyanyou** [nuxt/devtools#46]
Cannot start nuxt:  performance is not defined                    

  at node_modules/.pnpm/registry.npmmirror.com+@nuxt+devtools@0.1.0_nuxt@3.2.0/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:5196:16
  at callEachWith (node_modules/.pnpm/registry.npmmirror.com+hookable@5.4.2/node_modules/hookable/dist/index.mjs:46:5)
  at Hookable.callHookWith (node_modules/.pnpm/registry.npmmirror.com+hookable@5.4.2/node_modules/hookable/dist/index.mjs:156:7)
  at Hookable.callHook (node_modules/.pnpm/registry.npmmirror.com+hookable@5.4.2/node_modules/hookable/dist/index.mjs:148:17)
  at enableModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+devtools@0.1.0_nuxt@3.2.0/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:8415:14)
  at async normalizedModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.2.0/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.2.0/node_modules/@nuxt/kit/dist/index.mjs:435:15)
  at async initNuxt (node_modules/.pnpm/registry.npmmirror.com+nuxt@3.2.0_nnbwegkqhupcpxestea3eulahm/node_modules/nuxt/dist/index.mjs:2162:7)
  at async load (node_modules/.pnpm/registry.npmmirror.com+nuxi@3.2.0/node_modules/nuxi/dist/chunks/dev.mjs:6798:9)
  at async Object.invoke (node_modules/.pnpm/registry.npmmirror.com+nuxi@3.2.0/node_modules/nuxi/dist/chunks/dev.mjs:6859:5)
  at async _main (node_modules/.pnpm/registry.npmmirror.com+nuxi@3.2.0/node_modules/nuxi/dist/cli.mjs:51:20)

**Comment by harlan-zw** [comment]
Hey @huyanyou 

Can you confirm your node version? I think you need to be using Node 16.x

**Comment by huyanyou** [comment]
> 

node: v14.20.1

**Comment by huyanyou** [comment]
@harlan-zw
node: v14.20.1

**Comment by huyanyou** [comment]
@harlan-zw 
I have used the node version to 18 now, but after I installed devtools through the first method, I deleted node_modules and pnpm.lock.yml After deleting and reinstalling, the dependencies of nuxt cannot be installed

**Comment by huyanyou** [comment]
Cannot find module '/home/zks/.local/share/fnm/node-versions/v14.20.1/installation/lib/node_modules/@nuxt/devtools/dist/module.mjs'
Require stack:
- /home/zks/Projects/singzer-project/fit-official-website-nuxt/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/registry.npmmirror.com+jiti@1.17.0/node_modules/jiti/dist/jiti.js:1:246683)
  at resolveModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.1.2/node_modules/@nuxt/kit/dist/index.mjs:260:29)
  at normalizeModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.1.2/node_modules/@nuxt/kit/dist/index.mjs:451:18)
  at installModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.1.2/node_modules/@nuxt/kit/dist/index.mjs:434:47)
  at initNuxt (node_modules/.pnpm/registry.npmmirror.com+nuxt@3.1.2_nnbwegkqhupcpxestea3eulahm/node_modules/nuxt/dist/index.mjs:2047:13)
  at async loadNuxt (node_modules/.pnpm/registry.npmmirror.com+nuxt@3.1.2_nnbwegkqhupcpxestea3eulahm/node_modules/nuxt/dist/index.mjs:2080:5)
  at async loadNuxt (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.1.2/node_modules/@nuxt/kit/dist/index.mjs:522:19)
  at async Object.invoke (node_modules/.pnpm/registry.npmmirror.com+nuxi@3.1.2/node_modules/nuxi/dist/chunks/prepare.mjs:30:18)

**Comment by huyanyou** [comment]
@harlan-zw 
Cannot find module '/opt/homebrew/lib/node_modules/@nuxt/devtools/dist/module.mjs'

**Comment by harlan-zw** [comment]
Try run `npx nuxi@latest devtools enable` again or add it as a local dependency.

**Comment by huyanyou** [comment]
Cannot find module '/home/zks/.local/share/fnm/node-versions/v14.20.1/installation/lib/node_modules/@nuxt/devtools/dist/module.mjs'

**Comment by huyanyou** [comment]
@harlan-zw 
After installing devtools globally, all nuxt3 project installation dependencies will appear this way, and the template cannot be found

**Comment by huyanyou** [comment]
I use fnm to manage the node environment, but I didn’t find the 18 version in this directory. I was looking for 14. There are devtools under the 18 version

**Comment by harlan-zw** [comment]
Might be related to https://github.com/nuxt/devtools/issues/42

> You can remove from .nuxtrc in homedir as last resort.

**Comment by huyanyou** [comment]
There is no nuxtrc in my directory

**Comment by huyanyou** [comment]
I don't know how to let him look for templates in the directory of version 18

**Comment by huyanyou** [comment]
@harlan-zw 
There are devtools in the directory of the node18 version

**Comment by huyanyou** [comment]
It should be that "/home/zks/.local/share/fnm/node-versions/v14.20.1/installation/lib/node_modules/@nuxt/devtools/dist/module.mjs" cannot be found by executing the "nuxt prepare" command development tools

**Comment by TomatoSoup0126** [comment]
Same here.
It will happen on all nuxt project and no matter what node version.

**Comment by huyanyou** [comment]
how to resolve？

**Comment by huyanyou** [comment]
@TomatoSoup0126 
I also recreated the nuxt3 project, all of which cannot use nuxt commands, and they all have the same error

**Comment by EternalC0der** [comment]
.nuxtrc is located at `C:\users\%username%\` in **windows** (not sure about Unix)
If you want to completely remove nuxt devtools, try this
1. Run `npm remove -g `@nuxt/devtools` 
2. Delete `C:\users\%username%\.nuxtrc`

However, you can install @nuxt/devtools manually as a local package which seems more stable to me, and it doesn't affect other nuxt projects.

**Comment by huyanyou** [comment]
@EternalC0der 

I copied devtools from other node versions to version 14, but other errors occurred when the project started. I also tried to load devtools globally but it didn't work

**Comment by TomatoSoup0126** [comment]
> .nuxtrc is located at `C:\users\%username%\` in **windows** (not sure about Unix) If you want to completely remove nuxt devtools, try this
> 
> 1. Run `npm remove -g `@nuxt/devtools`
> 2. Delete `C:\users\%username%\.nuxtrc`
> 
@EternalC0der 
It's worked by follow the step!
By the way, .nuxtrc file on macOS is also located at `users\%username%\`.

**Comment by huyanyou** [comment]
> .nuxtrc is located at `C:\users\%username%\` in **windows** (not sure about Unix) If you want to completely remove nuxt devtools, try this
> 
> 1. Run `npm remove -g `@nuxt/devtools`
> 2. Delete `C:\users\%username%\.nuxtrc`
> 
> However, you can install @nuxt/devtools manually as a local package which seems more stable to me, and it doesn't affect other nuxt projects.

It's worked by follow the step!
By the way, .nuxtrc file on linux is also located at ~/.nuxtrc

**Comment by husayt** [comment]
i get the same error on windows/node18/pnpm and latest nuxt

![image](https://user-images.githubusercontent.com/1169324/218275885-085a09b4-f420-49c3-b4dc-02309e265087.png)

**Comment by antfu** [comment]
Closing as this issue is ambiguous with multiple context. 

For global install issue, please refer to https://github.com/nuxt/devtools/issues/42#issuecomment-1425483167

For other problems, please create new issues with reproductions. Thanks.
