### ISSUE TITLE
fix: Enabling timeline shows error: useAuth is not a function

### ISSUE THREAD

**Issue by martinszeltins** [nuxt/devtools#662]
### 🐛 The bug

If I enable the timeline then I get this error:

````
500 useAuth is not a function

at useAppInit (./composables/useAppInit.ts:8:3)
at setup (./app.js:31:5)
at _sfc_main.setup (./app.js:63:23)
at callWithErrorHandling (./node_modules/.pnpm/@vueruntime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19)
at setupStatefulComponent (./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7554:25)
at setupComponent (./node_modules/.pnpm/@vue+runtime-core@3.4.21/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7515:36)
at renderComponentVNode (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:15)
at Module.ssrRenderComponent (./node_modules/.pnpm/@vue+server-renderer@3.4.21_vue@3.4.21/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
at default (./node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@unocss+reset@0.59.4_floating-vue@5.2.2_unocss@0.59.4_vite@5.2.11/node_modules/nuxt/dist/app/components/nuxt-root.js:86:37)
````

If I disable the timeline then everything works.

### 🛠️ To reproduce

https://stackblitz.com/github/martinszeltins/nuxt-error-repro?file=app.vue

### 🌈 Expected behavior

Either it should always show the error or never show the error. And it is not clear what the error is about or what is the cause.

**Comment by hacknug** [comment]
I thought in my case the problem was related to layers but I see you don't use them on your repro project, so I'm guessing `timeline` tries to render/load pages/components before composables are available?
